# Generated by Django 4.2.11 on 2024-04-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review_rating_seller_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
