# Generated by Django 5.0.4 on 2024-04-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
