# Generated by Django 5.0.4 on 2024-05-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_shipping_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
