# Generated by Django 5.0.4 on 2024-05-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_brand_name_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
